AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance serving static HTML site from GitHub

Parameters:
  KeyName:
    Type: String
    Description: EC2 KeyPair name for SSH access

  GitRepo:
    Type: String
    Description: Public GitHub repo URL (e.g. https://github.com/username/repo.git)

  GitFolder:
    Type: String
    Default: ""
    Description: Optional: subfolder in repo to use as web root (leave blank if using root)

Resources:
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: ami-0c02fb55956c7d316  # Amazon Linux 2 (us-east-1)
      SecurityGroupIds:
        - !Ref WebSecurityGroup
      Tags:
        - Key: Name
          Value: GitHubHTMLServer
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd git
          systemctl start httpd
          systemctl enable httpd
          cd /var/www/html
          git clone ${GitRepo} site
          if [ "${GitFolder}" != "" ]; then
            cp -r site/${GitFolder}/* .
          else
            cp -r site/* .
          fi
          rm -rf site
          chown apache:apache -R /var/www/html

Outputs:
  WebsiteURL:
    Description: Your static site URL
    Value: !Sub "http://${WebServerInstance.PublicIp}"